### ISSUE TITLE
Proposal to Add Topics to Repo

### ISSUE THREAD

**Issue by DmitryRyumin** [yamathcy/ISMIR-2023-Papers#5]
Hi @yamathcy, 👋

I would like to propose adding the following topics to the repo to better categorize its content:

- music
- machine-learning
- music-recommendation
- music-technology
- music-generation
- audio-signal-processing
- music-analysis
- music-metadata
- musicology
- music-classification
- music-perception
- music-cognition
- ismir
- ismir2023

These topics will help organize the repo and make it easier for users to discover relevant content.

P.S.: In my [fork](https://github.com/DmitryRyumin/ISMIR-2023-Papers) of the repo I've already added these topics and updated the repository description to link to the original repo.

**Comment by yamathcy** [comment]
Hi, @DmitryRyumin, Sounds good!
You might have already known, each poster page shows its relevant topics (e.g. https://ismir2023program.ismir.net/poster_64.html P1-01: Exploring the Correspondence of Melodic Contour With Gesture in Raga Alap Singing -> Subjects (starting with primary): Knowledge-driven approaches to MIR -> computational ethnomusicology; MIR fundamentals and methodology -> multimodality). It can be helpful to categorize the papers.

**Comment by DmitryRyumin** [comment]
Hi @yamathcy,

Categorizing the papers based on relevant topics is indeed a helpful idea.
