### ISSUE TITLE
Add tutorial information?

### ISSUE THREAD

**Issue by WuYiming6526** [yamathcy/ISMIR-2023-Papers#7]
I would like to add a table about the tutorials, which includes the links to the (if available) web books.

Currently the only web book I could find is the DDSP tutorial.
[`https://intro2ddsp.github.io/`](https://intro2ddsp.github.io/)

Does anyone have information about other tutorials?

**Comment by yamathcy** [comment]
Hi, @WuYiming6526 Thank you for the suggestion.  
As far as I know, 
T1 https://laurabishop.github.io/MusicDiscoveryPupil/
T2 https://intro2ddsp.github.io/
T3 
part 1: https://docs.google.com/presentation/d/1AB27cUQzXaKbZlh3xtOCTWHR-PdWWXrF8K9xROFoNvk/edit?usp=sharing
part 2: https://docs.google.com/presentation/d/1qPPOfn8YDNIvpnGZFvx8UVYLuA8iXiHKK8OJgq7RSiM/edit?usp=sharing

T4 N/A
T5 N/A
T6 https://github.com/kymatio/ismir23-tutorial/tree/main/book

**Comment by WuYiming6526** [comment]
Thanks @yamathcy ! I will work on it.
